version: "3"

services:
  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - "3060:3000"
    networks:
      - glp
    restart: always

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - glp
    restart: always

  loki:
    image: grafana/loki:2.6.0
    command:
      - "--config.file=/etc/loki/local-config.yaml"
    ports:
      - "3100:3100"
    networks:
      - glp
    restart: always

networks:
  glp:
    driver: bridge
