version: "3"

services:
  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - "3060:3000"
    networks:
      - loki
    restart: always

  promtail:
    image: grafana/promtail:2.6.0
    volumes:
      - ./promtail.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
    restart: always

  loki:
    image: grafana/loki:2.6.0
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    networks:
      - loki
    restart: always

networks:
  loki:
