apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: hcwxd/kubernetes-demo
    command: ["/bin/sh", "-c", "env"]
    env:
    - name: MY_CONFIG_KEY
      valueFrom:
        configMapKeyRef:
          name: myconfigyaml
          key: k1
  restartPolicy: Never