name: testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/test_container

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r hello_test_container/requirements.txt

      - name: CI
        run: |
          python -m pytest hello_test_container

